package com.devhorizon.online.ggufchat.ui.theme

object Localization {
    private val translations = mapOf(
        "en" to mapOf(
            "app_name" to "GGUF Chat",
            "chat" to "Chat",
            "settings" to "Settings",
            "models" to "Models",
            "select_model" to "Select Model",
            "no_model" to "No model loaded",
            "load_model" to "Load Model",
            "download_model" to "Download Model",
            "model_url" to "Model URL (GGUF)",
            "file_name" to "File name (optional)",
            "download" to "Download",
            "download_hint" to "Paste a direct link to a .gguf file, e.g. from Hugging Face.",
            "search_models" to "Search Models Online",
            "search_keyword" to "Keyword (e.g. qwen, phi, llama)",
            "max_size_mb" to "Max size (MB)",
            "search" to "Search",
            "search_results" to "Results — select one to download:",
            "no_results" to "No results found",
            "no_limit" to "No limit",
            "importing_model" to "Importing model...",
            "model_imported" to "Model imported",
            "import_failed" to "Import failed",
            "downloading_model" to "Downloading model...",
            "model_downloaded" to "Model downloaded",
            "download_cancelled" to "Download cancelled",
            "download_failed" to "Download failed",
            "loading_model" to "Loading model...",
            "model_loaded_msg" to "Model loaded",
            "load_model_failed" to "Failed to load model",
            "please_load_model" to "Please load a model first",
            "error_msg" to "Error",
            "model_too_large" to "Model is too large for this device",
            "ready" to "Ready",
            "loading_memory" to "Loading into memory...",
            "copying_model" to "Copying model file...",
            "copying_mb" to "Copying...",
            "validating_file" to "Validating model file...",
            "download_complete" to "Download complete",
            "connecting" to "Connecting...",
            "downloading_mb" to "Downloading...",
            "no_storage" to "Not enough storage space",
            "invalid_gguf" to "Invalid GGUF file",
            "model_exists" to "Model with this name already exists",
            "invalid_url" to "URL must start with http:// or https://",
            "incomplete_download" to "Incomplete download",
            "cancelled" to "Cancelled",
            "ram" to "RAM",
            "free_ram" to "Free RAM",
            "ram_free" to "free",
            "ram_freed" to "RAM freed",
            "unsupported_arch" to "Model architecture not supported by this app build",
            "not_a_model" to "This file is not a complete language model",
            "tap_import_hint" to "Tap + to import a model file or use search/download",
            "model_loaded" to "Model loaded",
            "model_loading" to "Loading model...",
            "model_error" to "Failed to load model",
            "model_unloaded" to "Model unloaded",
            "unload_model" to "Unload model",
            "model_file_missing" to "Model file not found",
            "delete_model" to "Delete Model",
            "model_info" to "Model Info",
            "architecture" to "Architecture",
            "context_length" to "Context Length",
            "size" to "Size",
            "tensors" to "Tensors",
            "input_placeholder" to "Type a message...",
            "send" to "Send",
            "stop" to "Stop",
            "listening" to "Listening...",
            "voice_input" to "Voice Input",
            "tts" to "Text-to-Speech",
            "tts_enabled" to "Enable TTS",
            "tts_language" to "TTS Language",
            "tts_rate" to "Speech Rate",
            "stt_language" to "Voice Input Language",
            "system_prompt" to "System Prompt",
            "temperature" to "Temperature",
            "top_p" to "Top P",
            "max_tokens" to "Max Tokens",
            "context_size" to "Context Size",
            "threads" to "Threads",
            "auto_suggest" to "Auto-suggest replies",
            "suggestion_count" to "Number of Suggestions",
            "suggestion_doc_tokens" to "Document context for suggestions (tokens)",
            "suggestions" to "Suggestions",
            "new_suggestions" to "New Suggestions",
            "generating_suggestions" to "Generating suggestions...",
            "no_suggestions" to "No suggestions yet",
            "language" to "Language",
            "answer_language" to "Answer & suggestion language",
            "lang_auto" to "Same as interface",
            "english" to "English",
            "russian" to "Russian",
            "german" to "German",
            "light" to "Light",
            "dark" to "Dark",
            "green" to "Green",
            "orange" to "Orange",
            "light_blue" to "Light Blue",
            "yellow" to "Yellow",
            "new_chat" to "New Chat",
            "chat_history" to "Chat History",
            "delete_chat" to "Delete Chat",
            "cancel" to "Cancel",
            "ok" to "OK",
            "error" to "Error",
            "copy" to "Copy",
            "copied" to "Copied",
            "retry" to "Retry",
            "model_not_loaded" to "Please load a model first",
            "storage_warning" to "Not enough storage space",
            "loading_progress" to "Loading progress",
            "copying_model" to "Copying model file...",
            "loading_into_memory" to "Loading into memory...",
            "ready" to "Ready",
            "chat_template" to "Chat Template",
            "auto" to "Auto",
            "manual" to "Manual",
            "apply" to "Apply",
            "reset" to "Reset",
            "save" to "Save",
            "about" to "About",
            "version" to "Version",
            "model_selection" to "Model Selection",
            "inference_settings" to "Inference Settings",
            "voice_settings" to "Voice Settings",
            "suggestion_settings" to "Suggestion Settings",
            "general" to "General",
            "appearance" to "Appearance",
            "interface_section" to "Interface",
            "input_position" to "Input field position",
            "position_bottom" to "Bottom",
            "position_top" to "Top",
            "suggestions_layout" to "Suggestions layout",
            "layout_wrap" to "Multiple lines",
            "layout_single_row" to "Single row",
            "behavior" to "Behavior",
            "advanced" to "Advanced",
            "export_chat" to "Export Chat",
            "import_chat" to "Import Chat",
            "clear_history" to "Clear History",
            "search" to "Search",
            "search_placeholder" to "Search messages...",
            "no_results" to "No results found",
            "today" to "Today",
            "yesterday" to "Yesterday",
            "this_week" to "This Week",
            "older" to "Older",
            "message_copied" to "Message copied to clipboard",
            "model_deleted" to "Model deleted",
            "chat_deleted" to "Chat deleted",
            "confirm_delete" to "Are you sure you want to delete this?",
            "confirm" to "Confirm",
            "back" to "Back",
            "next" to "Next",
            "done" to "Done",
            "skip" to "Skip",
            "close" to "Close",
            "documents" to "Documents",
            "add_document" to "Add file",
            "attach" to "Attach",
            "attach_image" to "Attach image",
            "take_photo" to "Take photo",
            "image_attached" to "Image attached",
            "image_error" to "Failed to load the image",
            "remove_image" to "Remove image",
            "vision_unavailable" to "Image ignored: load a multimodal model with an mmproj projector",
            "not_a_projector" to "Not an mmproj projector file",
            "projector_importing" to "Importing projector...",
            "projector_imported" to "Projector imported",
            "projector_attached" to "Projector attached",
            "projector_removed" to "Projector removed",
            "projector" to "Projector (mmproj)",
            "attach_projector" to "Attach projector",
            "download_projector" to "Download projector",
            "remove_projector" to "Remove projector",
            "no_projector" to "No projector",
            "vision_ready" to "Image input ready",
            "text_only" to "Text only",
            "preparing_image" to "Analyzing image (may take minutes)...",
            "include_projectors" to "Search projectors (mmproj)",
            "projector_url" to "Projector URL (mmproj)",
            "loading_projector" to "Loading projector (mmproj)...",
            "document_added" to "Document attached",
            "documents_empty" to "No documents attached. Their text is passed to the model as context.",
            "doc_unsupported" to "Unsupported file type. Use txt, md, json or html.",
            "doc_truncated" to "truncated to fit context",
            "doc_read_error" to "Failed to read the file",
            "reading_document" to "Reading document...",
            "docs_budget_full" to "Document context budget is full. Remove a document first.",
            "remove_document" to "Remove document",
            "docs_context_hint" to "Context used",
            "docs_in_context" to "in context",
            "open" to "Open",
            "edit" to "Edit",
            "share" to "Share",
            "more" to "More",
            "less" to "Less",
            "show_more" to "Show more",
            "show_less" to "Show less",
            "expand" to "Expand",
            "collapse" to "Collapse",
            "refresh" to "Refresh",
            "reload" to "Reload",
            "update" to "Update",
            "download" to "Download",
            "upload" to "Upload",
            "install" to "Install",
            "uninstall" to "Uninstall",
            "enable" to "Enable",
            "disable" to "Disable",
            "on" to "On",
            "off" to "Off",
            "yes" to "Yes",
            "no" to "No",
            "maybe" to "Maybe",
            "unknown" to "Unknown",
            "loading" to "Loading...",
            "processing" to "Processing...",
            "waiting" to "Waiting...",
            "connecting" to "Connecting...",
            "disconnecting" to "Disconnecting...",
            "connected" to "Connected",
            "disconnected" to "Disconnected",
            "online" to "Online",
            "offline" to "Offline",
            "available" to "Available",
            "unavailable" to "Unavailable",
            "active" to "Active",
            "inactive" to "Inactive",
            "enabled" to "Enabled",
            "disabled" to "Disabled",
            "visible" to "Visible",
            "hidden" to "Hidden",
            "selected" to "Selected",
            "unselected" to "Unselected",
            "checked" to "Checked",
            "unchecked" to "Unchecked",
            "expanded" to "Expanded",
            "collapsed" to "Collapsed",
            "locked" to "Locked",
            "unlocked" to "Unlocked",
            "pinned" to "Pinned",
            "unpinned" to "Unpinned",
            "starred" to "Starred",
            "unstarred" to "Unstarred",
            "favorite" to "Favorite",
            "unfavorite" to "Unfavorite",
            "archived" to "Archived",
            "unarchived" to "Unarchived",
            "deleted" to "Deleted",
            "restored" to "Restored",
            "trashed" to "Trashed",
            "untrashed" to "Untrashed",
            "spam" to "Spam",
            "not_spam" to "Not Spam",
            "read" to "Read",
            "unread" to "Unread",
            "important" to "Important",
            "not_important" to "Not Important",
            "urgent" to "Urgent",
            "not_urgent" to "Not Urgent",
            "high" to "High",
            "medium" to "Medium",
            "low" to "Low",
            "critical" to "Critical",
            "warning" to "Warning",
            "info" to "Info",
            "success" to "Success",
            "failure" to "Failure",
            "pending" to "Pending",
            "completed" to "Completed",
            "in_progress" to "In Progress",
            "not_started" to "Not Started",
            "paused" to "Paused",
            "resumed" to "Resumed",
            "stopped" to "Stopped",
            "started" to "Started",
            "finished" to "Finished",
            "cancelled" to "Cancelled",
            "scheduled" to "Scheduled",
            "overdue" to "Overdue",
            "due" to "Due",
            "upcoming" to "Upcoming",
            "past" to "Past",
            "present" to "Present",
            "future" to "Future",
            "now" to "Now",
            "later" to "Later",
            "soon" to "Soon",
            "eventually" to "Eventually",
            "never" to "Never",
            "always" to "Always",
            "sometimes" to "Sometimes",
            "often" to "Often",
            "rarely" to "Rarely",
            "usually" to "Usually",
            "normally" to "Normally",
            "typically" to "Typically",
            "generally" to "Generally",
            "specifically" to "Specifically",
            "particularly" to "Particularly",
            "especially" to "Especially",
            "mainly" to "Mainly",
            "mostly" to "Mostly",
            "partly" to "Partly",
            "fully" to "Fully",
            "completely" to "Completely",
            "totally" to "Totally",
            "absolutely" to "Absolutely",
            "definitely" to "Definitely",
            "certainly" to "Certainly",
            "probably" to "Probably",
            "possibly" to "Possibly",
            "maybe" to "Maybe",
            "perhaps" to "Perhaps",
            "presumably" to "Presumably",
            "supposedly" to "Supposedly",
            "allegedly" to "Allegedly",
            "apparently" to "Apparently",
            "evidently" to "Evidently",
            "obviously" to "Obviously",
            "clearly" to "Clearly",
            "plainly" to "Plainly",
            "simply" to "Simply",
            "just" to "Just",
            "only" to "Only",
            "merely" to "Merely",
            "barely" to "Barely",
            "hardly" to "Hardly",
            "scarcely" to "Scarcely",
            "nearly" to "Nearly",
            "almost" to "Almost",
            "approximately" to "Approximately",
            "roughly" to "Roughly",
            "about" to "About",
            "around" to "Around",
            "approximately" to "Approximately",
            "exactly" to "Exactly",
            "precisely" to "Precisely",
            "accurately" to "Accurately",
            "correctly" to "Correctly",
            "incorrectly" to "Incorrectly",
            "wrongly" to "Wrongly",
            "rightly" to "Rightly",
            "justly" to "Justly",
            "unjustly" to "Unjustly",
            "fairly" to "Fairly",
            "unfairly" to "Unfairly",
            "equally" to "Equally",
            "unequally" to "Unequally",
            "similarly" to "Similarly",
            "differently" to "Differently",
            "likewise" to "Likewise",
            "otherwise" to "Otherwise",
            "else" to "Else",
            "instead" to "Instead",
            "rather" to "Rather",
            "alternatively" to "Alternatively",
            "conversely" to "Conversely",
            "inversely" to "Inversely",
            "oppositely" to "Oppositely",
            "contrarily" to "Contrarily",
            "contrastingly" to "Contrastingly",
            "comparatively" to "Comparatively",
            "relatively" to "Relatively",
            "absolutely" to "Absolutely",
            "conditionally" to "Conditionally",
            "unconditionally" to "Unconditionally",
            "definitely" to "Definitely",
            "indefinitely" to "Indefinitely",
            "temporarily" to "Temporarily",
            "permanently" to "Permanently",
            "briefly" to "Briefly",
            "shortly" to "Shortly",
            "momentarily" to "Momentarily",
            "instantly" to "Instantly",
            "immediately" to "Immediately",
            "promptly" to "Promptly",
            "quickly" to "Quickly",
            "rapidly" to "Rapidly",
            "swiftly" to "Swiftly",
            "speedily" to "Speedily",
            "slowly" to "Slowly",
            "gradually" to "Gradually",
            "steadily" to "Steadily",
            "continuously" to "Continuously",
            "continually" to "Continually",
            "constantly" to "Constantly",
            "consistently" to "Consistently",
            "persistently" to "Persistently",
            "repeatedly" to "Repeatedly",
            "frequently" to "Frequently",
            "infrequently" to "Infrequently",
            "occasionally" to "Occasionally",
            "periodically" to "Periodically",
            "regularly" to "Regularly",
            "irregularly" to "Irregularly",
            "sporadically" to "Sporadically",
            "randomly" to "Randomly",
            "arbitrarily" to "Arbitrarily",
            "haphazardly" to "Haphazardly",
            "chaotically" to "Chaotically",
            "orderly" to "Orderly",
            "disorderly" to "Disorderly",
            "methodically" to "Methodically",
            "systematically" to "Systematically",
            "logically" to "Logically",
            "illogically" to "Illogically",
            "rationally" to "Rationally",
            "irrationally" to "Irrationally",
            "reasonably" to "Reasonably",
            "unreasonably" to "Unreasonably",
            "sensibly" to "Sensibly",
            "insensibly" to "Insensibly",
            "wisely" to "Wisely",
            "foolishly" to "Foolishly",
            "intelligently" to "Intelligently",
            "unintelligently" to "Unintelligently",
            "cleverly" to "Cleverly",
            "stupidly" to "Stupidly",
            "brilliantly" to "Brilliantly",
            "dully" to "Dully",
            "brightly" to "Brightly",
            "darkly" to "Darkly",
            "lightly" to "Lightly",
            "heavily" to "Heavily",
            "strongly" to "Strongly",
            "weakly" to "Weakly",
            "powerfully" to "Powerfully",
            "powerlessly" to "Powerlessly",
            "forcefully" to "Forcefully",
            "gently" to "Gently",
            "roughly" to "Roughly",
            "smoothly" to "Smoothly",
            "softly" to "Softly",
            "loudly" to "Loudly",
            "quietly" to "Quietly",
            "silently" to "Silently",
            "noisily" to "Noisily",
            "peacefully" to "Peacefully",
            "violently" to "Violently",
            "calmly" to "Calmly",
            "angrily" to "Angrily",
            "happily" to "Happily",
            "sadly" to "Sadly",
            "joyfully" to "Joyfully",
            "sorrowfully" to "Sorrowfully",
            "cheerfully" to "Cheerfully",
            "gloomily" to "Gloomily",
            "merrily" to "Merrily",
            "solemnly" to "Solemnly",
            "seriously" to "Seriously",
            "jokingly" to "Jokingly",
            "playfully" to "Playfully",
            "seriously" to "Seriously",
            "earnestly" to "Earnestly",
            "sincerely" to "Sincerely",
            "insincerely" to "Insincerely",
            "genuinely" to "Genuinely",
            "falsely" to "Falsely",
            "truly" to "Truly",
            "untruly" to "Untruly",
            "really" to "Really",
            "unreally" to "Unreally",
            "actually" to "Actually",
            "virtually" to "Virtually",
            "practically" to "Practically",
            "theoretically" to "Theoretically",
            "hypothetically" to "Hypothetically",
            "ideally" to "Ideally",
            "realistically" to "Realistically",
            "unrealistically" to "Unrealistically",
            "fantastically" to "Fantastically",
            "amazingly" to "Amazingly",
            "astonishingly" to "Astonishingly",
            "surprisingly" to "Surprisingly",
            "shockingly" to "Shockingly",
            "stunningly" to "Stunningly",
            "startlingly" to "Startlingly",
            "bewilderingly" to "Bewilderingly",
            "confusingly" to "Confusingly",
            "puzzlingly" to "Puzzlingly",
            "mysteriously" to "Mysteriously",
            "strangely" to "Strangely",
            "oddly" to "Oddly",
            "weirdly" to "Weirdly",
            "peculiarly" to "Peculiarly",
            "curiously" to "Curiously",
            "interestingly" to "Interestingly",
            "uninterestingly" to "Uninterestingly",
            "boringly" to "Boringly",
            "excitingly" to "Excitingly",
            "unexcitingly" to "Unexcitingly",
            "thrillingly" to "Thrillingly",
            "chillingly" to "Chillingly",
            "spine-tinglingly" to "Spine-tinglingly",
            "hair-raisingly" to "Hair-raisingly",
            "heart-stoppingly" to "Heart-stoppingly",
            "breath-takingly" to "Breath-takingly",
            "jaw-droppingly" to "Jaw-droppingly",
            "eye-poppingly" to "Eye-poppingly",
            "mind-blowingly" to "Mind-blowingly",
            "earth-shatteringly" to "Earth-shatteringly",
            "world-changingly" to "World-changingly",
            "life-changingly" to "Life-changingly",
            "fatefully" to "Fatefully",
            "destinedly" to "Destinedly",
            "doomedly" to "Doomedly",
            "cursedly" to "Cursedly",
            "blessedly" to "Blessedly",
            "luckily" to "Luckily",
            "unluckily" to "Unluckily",
            "fortunately" to "Fortunately",
            "unfortunately" to "Unfortunately",
            "happily" to "Happily",
            "unhappily" to "Unhappily",
            "fortunately" to "Fortunately",
            "unfortunately" to "Unfortunately",
            "sadly" to "Sadly",
            "tragically" to "Tragically",
            "comically" to "Comically",
            "ironically" to "Ironically",
            "sarcastically" to "Sarcastically",
            "satirically" to "Satirically",
            "parodically" to "Parodically",
            "humorously" to "Humorously",
            "seriously" to "Seriously",
            "jokingly" to "Jokingly",
            "facetiously" to "Facetiously",
            "flippantly" to "Flippantly",
            "glibly" to "Glibly",
            "cheekily" to "Cheekily",
            "impudently" to "Impudently",
            "brazenly" to "Brazenly",
            "boldly" to "Boldly",
            "timidly" to "Timidly",
            "shyly" to "Shyly",
            "bashfully" to "Bashfully",
            "modestly" to "Modestly",
            "immodestly" to "Immodestly",
            "humbly" to "Humbly",
            "proudly" to "Proudly",
            "arrogantly" to "Arrogantly",
            "haughtily" to "Haughtily",
            "snobbishly" to "Snobbishly",
            "pretentiously" to "Pretentiously",
            "ostentatiously" to "Ostentatiously",
            "showily" to "Showily",
            "flashily" to "Flashily",
            "gaudily" to "Gaudily",
            "tastefully" to "Tastefully",
            "distastefully" to "Distastefully",
            "elegantly" to "Elegantly",
            "inelegantly" to "Inelegantly",
            "gracefully" to "Gracefully",
            "gracelessly" to "Gracelessly",
            "beautifully" to "Beautifully",
            "uglily" to "Uglily",
            "handsomely" to "Handsomely",
            "plainly" to "Plainly",
            "attractively" to "Attractively",
            "unattractively" to "Unattractively",
            "appealingly" to "Appealingly",
            "unappealingly" to "Unappealingly",
            "charmingly" to "Charmingly",
            "uncharmingly" to "Uncharmingly",
            "delightfully" to "Delightfully",
            "disgustingly" to "Disgustingly",
            "repulsively" to "Repulsively",
            "attractively" to "Attractively",
            "repellently" to "Repellently",
            "offensively" to "Offensively",
            "defensively" to "Defensively",
            "aggressively" to "Aggressively",
            "passively" to "Passively",
            "actively" to "Actively",
            "inactively" to "Inactively",
            "energetically" to "Energetically",
            "lethargically" to "Lethargically",
            "vigorously" to "Vigorously",
            "listlessly" to "Listlessly",
            "dynamically" to "Dynamically",
            "statically" to "Statically",
            "kinetically" to "Kinetically",
            "potentially" to "Potentially",
            "actually" to "Actually",
            "virtually" to "Virtually",
            "essentially" to "Essentially",
            "basically" to "Basically",
            "fundamentally" to "Fundamentally",
            "primarily" to "Primarily",
            "secondarily" to "Secondarily",
            "mainly" to "Mainly",
            "chiefly" to "Chiefly",
            "principally" to "Principally",
            "mostly" to "Mostly",
            "largely" to "Largely",
            "partly" to "Partly",
            "partially" to "Partially",
            "wholly" to "Wholly",
            "entirely" to "Entirely",
            "fully" to "Fully",
            "completely" to "Completely",
            "totally" to "Totally",
            "utterly" to "Utterly",
            "absolutely" to "Absolutely",
            "thoroughly" to "Thoroughly",
            "exhaustively" to "Exhaustively",
            "comprehensively" to "Comprehensively",
            "extensively" to "Extensively",
            "intensively" to "Intensively",
            "in-depth" to "In-depth",
            "superficially" to "Superficially",
            "cursorily" to "Cursorily",
            "briefly" to "Briefly",
            "lengthily" to "Lengthily",
            "prolongedly" to "Prolongedly",
            "endlessly" to "Endlessly",
            "ceaselessly" to "Ceaselessly",
            "incessantly" to "Incessantly",
            "unceasingly" to "Unceasingly",
            "interminably" to "Interminably",
            "eternally" to "Eternally",
            "temporarily" to "Temporarily",
            "briefly" to "Briefly",
            "momentarily" to "Momentarily",
            "fleetingly" to "Fleetingly",
            "transiently" to "Transiently",
            "transitorily" to "Transitorily",
            "ephemerally" to "Ephemerally",
            "fugitively" to "Fugitively",
            "passingly" to "Passingly",
            "temporarily" to "Temporarily",
            "provisionally" to "Provisionally",
            "tentatively" to "Tentatively",
            "conditionally" to "Conditionally",
            "unconditionally" to "Unconditionally",
            "definitely" to "Definitely",
            "indefinitely" to "Indefinitely",
            "permanently" to "Permanently",
            "irrevocably" to "Irrevocably",
            "irreversibly" to "Irreversibly",
            "irreparably" to "Irreparably",
            "irremediably" to "Irremediably",
            "irretrievably" to "Irretrievably",
            "irrecoverably" to "Irrecoverably",
            "irredeemably" to "Irredeemably",
            "irrevocably" to "Irrevocably",
            "unalterably" to "Unalterably",
            "unchangeably" to "Unchangeably",
            "immutably" to "Immutably",
            "invariably" to "Invariably",
            "constantly" to "Constantly",
            "permanently" to "Permanently",
            "lastingly" to "Lastingly",
            "enduringly" to "Enduringly",
            "perennially" to "Perennially",
            "everlastingly" to "Everlastingly",
            "eternally" to "Eternally",
            "infinitely" to "Infinitely",
            "boundlessly" to "Boundlessly",
            "limitlessly" to "Limitlessly",
            "endlessly" to "Endlessly",
            "ceaselessly" to "Ceaselessly",
            "interminably" to "Interminably",
            "inexhaustibly" to "Inexhaustibly",
            "inexhaustibly" to "Inexhaustibly",
            "inexhaustibly" to "Inexhaustibly"
        ),
        "de" to mapOf(
            "app_name" to "GGUF Chat",
            "chat" to "Chat",
            "settings" to "Einstellungen",
            "models" to "Modelle",
            "select_model" to "Modell auswählen",
            "no_model" to "Kein Modell geladen",
            "load_model" to "Modell laden",
            "download_model" to "Modell herunterladen",
            "model_url" to "Modell-URL (GGUF)",
            "file_name" to "Dateiname (optional)",
            "download" to "Herunterladen",
            "download_hint" to "Füge einen direkten Link zu einer .gguf-Datei ein, z. B. von Hugging Face.",
            "search_models" to "Modelle online suchen",
            "search_keyword" to "Stichwort (z. B. qwen, phi, llama)",
            "max_size_mb" to "Max. Größe (MB)",
            "search" to "Suchen",
            "search_results" to "Ergebnisse — zum Herunterladen auswählen:",
            "no_results" to "Keine Ergebnisse gefunden",
            "no_limit" to "Keine Grenze",
            "importing_model" to "Modell wird importiert...",
            "model_imported" to "Modell importiert",
            "import_failed" to "Import fehlgeschlagen",
            "downloading_model" to "Modell wird heruntergeladen...",
            "model_downloaded" to "Modell heruntergeladen",
            "download_cancelled" to "Download abgebrochen",
            "download_failed" to "Download fehlgeschlagen",
            "loading_model" to "Modell wird geladen...",
            "model_loaded_msg" to "Modell geladen",
            "load_model_failed" to "Modell konnte nicht geladen werden",
            "please_load_model" to "Bitte laden Sie zuerst ein Modell",
            "error_msg" to "Fehler",
            "model_too_large" to "Modell ist für dieses Gerät zu groß",
            "ready" to "Bereit",
            "loading_memory" to "Wird in den Speicher geladen...",
            "copying_model" to "Modell-Datei wird kopiert...",
            "copying_mb" to "Kopiere...",
            "validating_file" to "Modell-Datei wird geprüft...",
            "download_complete" to "Download abgeschlossen",
            "connecting" to "Verbinde...",
            "downloading_mb" to "Lade herunter...",
            "no_storage" to "Nicht genügend Speicherplatz",
            "invalid_gguf" to "Ungültige GGUF-Datei",
            "model_exists" to "Modell mit diesem Namen existiert bereits",
            "invalid_url" to "URL muss mit http:// oder https:// beginnen",
            "incomplete_download" to "Unvollständiger Download",
            "cancelled" to "Abgebrochen",
            "ram" to "RAM",
            "free_ram" to "RAM freigeben",
            "ram_free" to "frei",
            "ram_freed" to "RAM freigegeben",
            "unsupported_arch" to "Modellarchitektur wird von diesem Build nicht unterstützt",
            "not_a_model" to "Diese Datei ist kein vollständiges Sprachmodell",
            "tap_import_hint" to "Tippe auf +, um eine Modell-Datei zu importieren, oder Suche/Download nutzen",
            "model_loaded" to "Modell geladen",
            "model_loading" to "Modell wird geladen...",
            "model_error" to "Modell konnte nicht geladen werden",
            "model_unloaded" to "Modell entladen",
            "unload_model" to "Modell entladen",
            "model_file_missing" to "Modelldatei nicht gefunden",
            "delete_model" to "Modell löschen",
            "model_info" to "Modellinfo",
            "architecture" to "Architektur",
            "context_length" to "Kontextlänge",
            "size" to "Größe",
            "tensors" to "Tensoren",
            "input_placeholder" to "Nachricht eingeben...",
            "send" to "Senden",
            "stop" to "Stopp",
            "listening" to "Hören...",
            "voice_input" to "Spracheingabe",
            "tts" to "Sprachausgabe",
            "tts_enabled" to "Sprachausgabe aktivieren",
            "tts_language" to "Sprachausgabesprache",
            "tts_rate" to "Sprechgeschwindigkeit",
            "stt_language" to "Spracheingabesprache",
            "system_prompt" to "System-Prompt",
            "temperature" to "Temperatur",
            "top_p" to "Top P",
            "max_tokens" to "Max Tokens",
            "context_size" to "Kontextgröße",
            "threads" to "Threads",
            "auto_suggest" to "Antwortvorschläge automatisch",
            "suggestion_count" to "Anzahl der Vorschläge",
            "suggestion_doc_tokens" to "Dokumentkontext für Vorschläge (Token)",
            "suggestions" to "Vorschläge",
            "new_suggestions" to "Neue Vorschläge",
            "generating_suggestions" to "Vorschläge werden generiert...",
            "no_suggestions" to "Noch keine Vorschläge",
            "language" to "Sprache",
            "answer_language" to "Sprache für Antworten & Vorschläge",
            "lang_auto" to "Wie Oberfläche",
            "english" to "Englisch",
            "russian" to "Russisch",
            "german" to "Deutsch",
            "light" to "Hell",
            "dark" to "Dunkel",
            "green" to "Grün",
            "orange" to "Orange",
            "light_blue" to "Hellblau",
            "yellow" to "Gelb",
            "new_chat" to "Neuer Chat",
            "chat_history" to "Chatverlauf",
            "delete_chat" to "Chat löschen",
            "cancel" to "Abbrechen",
            "ok" to "OK",
            "error" to "Fehler",
            "copy" to "Kopieren",
            "copied" to "Kopiert",
            "retry" to "Wiederholen",
            "model_not_loaded" to "Bitte laden Sie zuerst ein Modell",
            "storage_warning" to "Nicht genügend Speicherplatz",
            "loading_progress" to "Ladevorgang",
            "copying_model" to "Modell wird kopiert...",
            "loading_into_memory" to "Wird in den Speicher geladen...",
            "ready" to "Bereit",
            "chat_template" to "Chat-Vorlage",
            "auto" to "Automatisch",
            "manual" to "Manuell",
            "apply" to "Anwenden",
            "reset" to "Zurücksetzen",
            "save" to "Speichern",
            "about" to "Über",
            "version" to "Version",
            "model_selection" to "Modellauswahl",
            "inference_settings" to "Inferenzeinstellungen",
            "voice_settings" to "Spracheinstellungen",
            "suggestion_settings" to "Vorschlagseinstellungen",
            "general" to "Allgemein",
            "appearance" to "Erscheinungsbild",
            "interface_section" to "Oberfläche",
            "input_position" to "Position des Eingabefelds",
            "position_bottom" to "Unten",
            "position_top" to "Oben",
            "suggestions_layout" to "Layout der Vorschläge",
            "layout_wrap" to "Mehrere Zeilen",
            "layout_single_row" to "Einzelne Zeile",
            "behavior" to "Verhalten",
            "advanced" to "Erweitert",
            "export_chat" to "Chat exportieren",
            "import_chat" to "Chat importieren",
            "clear_history" to "Verlauf löschen",
            "search" to "Suchen",
            "search_placeholder" to "Nachrichten suchen...",
            "no_results" to "Keine Ergebnisse gefunden",
            "today" to "Heute",
            "yesterday" to "Gestern",
            "this_week" to "Diese Woche",
            "older" to "Älter",
            "message_copied" to "Nachricht in die Zwischenablage kopiert",
            "model_deleted" to "Modell gelöscht",
            "chat_deleted" to "Chat gelöscht",
            "confirm_delete" to "Möchten Sie dies wirklich löschen?",
            "confirm" to "Bestätigen",
            "back" to "Zurück",
            "next" to "Weiter",
            "done" to "Fertig",
            "skip" to "Überspringen",
            "close" to "Schließen",
            "documents" to "Dokumente",
            "add_document" to "Datei hinzufügen",
            "attach" to "Anhängen",
            "attach_image" to "Bild anhängen",
            "take_photo" to "Foto aufnehmen",
            "image_attached" to "Bild angehängt",
            "image_error" to "Bild konnte nicht geladen werden",
            "remove_image" to "Bild entfernen",
            "vision_unavailable" to "Bild ignoriert: multimodales Modell mit mmproj laden",
            "not_a_projector" to "Keine mmproj-Projektordatei",
            "projector_importing" to "Projektor wird importiert...",
            "projector_imported" to "Projektor importiert",
            "projector_attached" to "Projektor angehängt",
            "projector_removed" to "Projektor entfernt",
            "projector" to "Projektor (mmproj)",
            "attach_projector" to "Projektor anhängen",
            "download_projector" to "Projektor herunterladen",
            "remove_projector" to "Projektor entfernen",
            "no_projector" to "Kein Projektor",
            "vision_ready" to "Bildeingabe bereit",
            "text_only" to "Nur Text",
            "preparing_image" to "Bild wird analysiert (kann Minuten dauern)...",
            "include_projectors" to "Projektoren suchen (mmproj)",
            "projector_url" to "Projektor-URL (mmproj)",
            "loading_projector" to "Projektor wird geladen (mmproj)...",
            "document_added" to "Dokument hinzugefügt",
            "documents_empty" to "Keine Dokumente angehängt. Ihr Text dient dem Modell als Kontext.",
            "doc_unsupported" to "Nicht unterstützter Dateityp. Nutze txt, md, json oder html.",
            "doc_truncated" to "für den Kontext gekürzt",
            "doc_read_error" to "Datei konnte nicht gelesen werden",
            "reading_document" to "Dokument wird gelesen...",
            "docs_budget_full" to "Kontextbudget für Dokumente ist voll. Entferne zuerst ein Dokument.",
            "remove_document" to "Dokument entfernen",
            "docs_context_hint" to "Genutzter Kontext",
            "docs_in_context" to "im Kontext",
            "open" to "Öffnen",
            "edit" to "Bearbeiten",
            "share" to "Teilen",
            "more" to "Mehr",
            "less" to "Weniger",
            "show_more" to "Mehr anzeigen",
            "show_less" to "Weniger anzeigen",
            "expand" to "Erweitern",
            "collapse" to "Einklappen",
            "refresh" to "Aktualisieren",
            "reload" to "Neu laden",
            "update" to "Aktualisieren",
            "download" to "Herunterladen",
            "upload" to "Hochladen",
            "install" to "Installieren",
            "uninstall" to "Deinstallieren",
            "enable" to "Aktivieren",
            "disable" to "Deaktivieren",
            "on" to "An",
            "off" to "Aus",
            "yes" to "Ja",
            "no" to "Nein",
            "maybe" to "Vielleicht",
            "unknown" to "Unbekannt",
            "loading" to "Laden...",
            "processing" to "Verarbeitung...",
            "waiting" to "Warten...",
            "connecting" to "Verbinden...",
            "disconnecting" to "Trennen...",
            "connected" to "Verbunden",
            "disconnected" to "Getrennt",
            "online" to "Online",
            "offline" to "Offline",
            "available" to "Verfügbar",
            "unavailable" to "Nicht verfügbar",
            "active" to "Aktiv",
            "inactive" to "Inaktiv",
            "enabled" to "Aktiviert",
            "disabled" to "Deaktiviert",
            "visible" to "Sichtbar",
            "hidden" to "Versteckt",
            "selected" to "Ausgewählt",
            "unselected" to "Nicht ausgewählt",
            "checked" to "Geprüft",
            "unchecked" to "Nicht geprüft",
            "expanded" to "Erweitert",
            "collapsed" to "Eingeklappt",
            "locked" to "Gesperrt",
            "unlocked" to "Entsperrt",
            "pinned" to "Angepinnt",
            "unpinned" to "Nicht angepinnt",
            "starred" to "Markiert",
            "unstarred" to "Nicht markiert",
            "favorite" to "Favorit",
            "unfavorite" to "Kein Favorit",
            "archived" to "Archiviert",
            "unarchived" to "Nicht archiviert",
            "deleted" to "Gelöscht",
            "restored" to "Wiederhergestellt",
            "trashed" to "Im Papierkorb",
            "untrashed" to "Nicht im Papierkorb",
            "spam" to "Spam",
            "not_spam" to "Kein Spam",
            "read" to "Gelesen",
            "unread" to "Ungelesen",
            "important" to "Wichtig",
            "not_important" to "Nicht wichtig",
            "urgent" to "Dringend",
            "not_urgent" to "Nicht dringend",
            "high" to "Hoch",
            "medium" to "Mittel",
            "low" to "Niedrig",
            "critical" to "Kritisch",
            "warning" to "Warnung",
            "info" to "Info",
            "success" to "Erfolg",
            "failure" to "Fehler",
            "pending" to "Ausstehend",
            "completed" to "Abgeschlossen",
            "in_progress" to "In Bearbeitung",
            "not_started" to "Nicht gestartet",
            "paused" to "Pausiert",
            "resumed" to "Fortgesetzt",
            "stopped" to "Gestoppt",
            "started" to "Gestartet",
            "finished" to "Beendet",
            "cancelled" to "Abgebrochen",
            "scheduled" to "Geplant",
            "overdue" to "Überfällig",
            "due" to "Fällig",
            "upcoming" to "Bevorstehend",
            "past" to "Vergangen",
            "present" to "Gegenwart",
            "future" to "Zukunft",
            "now" to "Jetzt",
            "later" to "Später",
            "soon" to "Bald",
            "eventually" to "Schließlich",
            "never" to "Nie",
            "always" to "Immer",
            "sometimes" to "Manchmal",
            "often" to "Oft",
            "rarely" to "Selten",
            "usually" to "Normalerweise",
            "normally" to "Normalerweise",
            "typically" to "Typischerweise",
            "generally" to "Im Allgemeinen",
            "specifically" to "Speziell",
            "particularly" to "Besonders",
            "especially" to "Besonders",
            "mainly" to "Hauptsächlich",
            "mostly" to "Meistens",
            "partly" to "Teilweise",
            "fully" to "Vollständig",
            "completely" to "Vollständig",
            "totally" to "Total",
            "absolutely" to "Absolut",
            "definitely" to "Definitiv",
            "certainly" to "Sicherlich",
            "probably" to "Wahrscheinlich",
            "possibly" to "Möglicherweise",
            "maybe" to "Vielleicht",
            "perhaps" to "Vielleicht",
            "presumably" to "Vermutlich",
            "supposedly" to "Angeblich",
            "allegedly" to "Angeblich",
            "apparently" to "Offensichtlich",
            "evidently" to "Offensichtlich",
            "obviously" to "Offensichtlich",
            "clearly" to "Offensichtlich",
            "plainly" to "Einfach",
            "simply" to "Einfach",
            "just" to "Nur",
            "only" to "Nur",
            "merely" to "Nur",
            "barely" to "Kaum",
            "hardly" to "Kaum",
            "scarcely" to "Kaum",
            "nearly" to "Fast",
            "almost" to "Fast",
            "approximately" to "Ungefähr",
            "roughly" to "Ungefähr",
            "about" to "Etwa",
            "around" to "Etwa",
            "exactly" to "Genau",
            "precisely" to "Genau",
            "accurately" to "Genau",
            "correctly" to "Richtig",
            "incorrectly" to "Falsch",
            "wrongly" to "Falsch",
            "rightly" to "Richtig",
            "justly" to "Gerecht",
            "unjustly" to "Ungerecht",
            "fairly" to "Fair",
            "unfairly" to "Unfair",
            "equally" to "Gleich",
            "unequally" to "Ungleich",
            "similarly" to "Ähnlich",
            "differently" to "Anders",
            "likewise" to "Ebenso",
            "otherwise" to "Andernfalls",
            "else" to "Sonst",
            "instead" to "Stattdessen",
            "rather" to "Eher",
            "alternatively" to "Alternativ",
            "conversely" to "Umgekehrt",
            "inversely" to "Umgekehrt",
            "oppositely" to "Entgegengesetzt",
            "contrarily" to "Entgegengesetzt",
            "contrastingly" to "Im Gegensatz",
            "comparatively" to "Vergleichsweise",
            "relatively" to "Relativ",
            "conditionally" to "Bedingt",
            "unconditionally" to "Unbedingt",
            "indefinitely" to "Unbestimmt",
            "temporarily" to "Vorübergehend",
            "permanently" to "Dauerhaft",
            "briefly" to "Kurz",
            "shortly" to "Bald",
            "momentarily" to "Kurz",
            "instantly" to "Sofort",
            "immediately" to "Sofort",
            "promptly" to "Prompt",
            "quickly" to "Schnell",
            "rapidly" to "Schnell",
            "swiftly" to "Schnell",
            "speedily" to "Schnell",
            "slowly" to "Langsam",
            "gradually" to "Allmählich",
            "steadily" to "Stetig",
            "continuously" to "Kontinuierlich",
            "continually" to "Kontinuierlich",
            "constantly" to "Ständig",
            "consistently" to "Konsequent",
            "persistently" to "Beharrlich",
            "repeatedly" to "Wiederholt",
            "frequently" to "Häufig",
            "infrequently" to "Selten",
            "occasionally" to "Gelegentlich",
            "periodically" to "Periodisch",
            "regularly" to "Regelmäßig",
            "irregularly" to "Unregelmäßig",
            "sporadically" to "Gelegentlich",
            "randomly" to "Zufällig",
            "arbitrarily" to "Willkürlich",
            "haphazardly" to "Planlos",
            "chaotically" to "Chaotisch",
            "orderly" to "Ordnungsgemäß",
            "disorderly" to "Unordentlich",
            "methodically" to "Methodisch",
            "systematically" to "Systematisch",
            "logically" to "Logisch",
            "illogically" to "Unlogisch",
            "rationally" to "Vernünftig",
            "irrationally" to "Unvernünftig",
            "reasonably" to "Vernünftig",
            "unreasonably" to "Unvernünftig",
            "sensibly" to "Vernünftig",
            "insensibly" to "Unvernünftig",
            "wisely" to "Weise",
            "foolishly" to "Töricht",
            "intelligently" to "Intelligent",
            "unintelligently" to "Unintelligent",
            "cleverly" to "Clever",
            "stupidly" to "Dumm",
            "brilliantly" to "Brillant",
            "dully" to "Stumpf",
            "brightly" to "Hell",
            "darkly" to "Dunkel",
            "lightly" to "Leicht",
            "heavily" to "Schwer",
            "strongly" to "Stark",
            "weakly" to "Schwach",
            "powerfully" to "Mächtig",
            "powerlessly" to "Ohnmächtig",
            "forcefully" to "Gewaltsam",
            "gently" to "Sanft",
            "roughly" to "Grob",
            "smoothly" to "Reibungslos",
            "softly" to "Leise",
            "loudly" to "Laut",
            "quietly" to "Leise",
            "silently" to "Still",
            "noisily" to "Lärmend",
            "peacefully" to "Friedlich",
            "violently" to "Gewaltsam",
            "calmly" to "Ruhig",
            "angrily" to "Wütend",
            "happily" to "Glücklich",
            "sadly" to "Traurig",
            "joyfully" to "Freudig",
            "sorrowfully" to "Traurig",
            "cheerfully" to "Fröhlich",
            "gloomily" to "Düster",
            "merrily" to "Fröhlich",
            "solemnly" to "Feierlich",
            "seriously" to "Ernst",
            "jokingly" to "Scherzhaft",
            "facetiously" to "Albern",
            "flippantly" to "Frivol",
            "glibly" to "Oberflächlich",
            "cheekily" to "Frech",
            "impudently" to "Unverschämt",
            "brazenly" to "Schamlos",
            "boldly" to "Kühn",
            "timidly" to "Schüchtern",
            "shyly" to "Schüchtern",
            "bashfully" to "Schüchtern",
            "modestly" to "Bescheiden",
            "immodestly" to "Unbescheiden",
            "humbly" to "Demütig",
            "proudly" to "Stolz",
            "arrogantly" to "Arrogant",
            "haughtily" to "Hochmütig",
            "snobbishly" to "Snobistisch",
            "pretentiously" to "Anmaßend",
            "ostentatiously" to "Prahlerisch",
            "showily" to "Auffällig",
            "flashily" to "Auffällig",
            "gaudily" to "Knallig",
            "tastefully" to "Geschmackvoll",
            "distastefully" to "Geschmacklos",
            "elegantly" to "Elegant",
            "inelegantly" to "Un elegant",
            "gracefully" to "Anmutig",
            "gracelessly" to "Unbeholfen",
            "beautifully" to "Schön",
            "uglily" to "Hässlich",
            "handsomely" to "Hübsch",
            "plainly" to "Einfach",
            "attractively" to "Attraktiv",
            "unattractively" to "Unattraktiv",
            "appealingly" to "Ansprechend",
            "unappealingly" to "Unansprechend",
            "charmingly" to "Charmant",
            "uncharmingly" to "Uncharmant",
            "delightfully" to "Entzückend",
            "disgustingly" to "Ekelhaft",
            "repulsively" to "Abstoßend",
            "repellently" to "Abstoßend",
            "offensively" to "Beleidigend",
            "defensively" to "Verteidigend",
            "aggressively" to "Aggressiv",
            "passively" to "Passiv",
            "actively" to "Aktiv",
            "inactively" to "Inaktiv",
            "energetically" to "Energisch",
            "lethargically" to "Lethargisch",
            "vigorously" to "Energisch",
            "listlessly" to "Lustlos",
            "dynamically" to "Dynamisch",
            "statically" to "Statisch",
            "kinetically" to "Kinetisch",
            "potentially" to "Potenziell",
            "essentially" to "Im Wesentlichen",
            "basically" to "Grundsätzlich",
            "fundamentally" to "Grundlegend",
            "primarily" to "In erster Linie",
            "secondarily" to "Sekundär",
            "chiefly" to "Hauptsächlich",
            "principally" to "Prinzipiell",
            "largely" to "Großteils",
            "partially" to "Teilweise",
            "wholly" to "Gänzlich",
            "entirely" to "Gänzlich",
            "utterly" to "Völlig",
            "thoroughly" to "Gründlich",
            "exhaustively" to "Erschöpfend",
            "comprehensively" to "Umfassend",
            "extensively" to "Umfangreich",
            "intensively" to "Intensiv",
            "in-depth" to "Tiefgehend",
            "superficially" to "Oberflächlich",
            "cursorily" to "Flüchtig",
            "lengthily" to "Länglich",
            "prolongedly" to "Lange",
            "endlessly" to "Endlos",
            "ceaselessly" to "Unaufhörlich",
            "incessantly" to "Unaufhörlich",
            "unceasingly" to "Unaufhörlich",
            "interminably" to "Endlos",
            "eternally" to "Ewig",
            "irrevocably" to "Unwiderruflich",
            "irreversibly" to "Unumkehrbar",
            "irreparably" to "Unreparabel",
            "irremediably" to "Unheilbar",
            "irretrievably" to "Unwiederbringlich",
            "irrecoverably" to "Unwiederbringlich",
            "irredeemably" to "Unwiederbringlich",
            "unalterably" to "Unveränderlich",
            "unchangeably" to "Unveränderlich",
            "immutably" to "Unveränderlich",
            "invariably" to "Unveränderlich",
            "lastingly" to "Dauerhaft",
            "enduringly" to "Dauerhaft",
            "perennially" to "Dauerhaft",
            "everlastingly" to "Ewig",
            "infinitely" to "Unendlich",
            "boundlessly" to "Grenzenlos",
            "limitlessly" to "Grenzenlos",
            "inexhaustibly" to "Unerschöpflich"
        ),
        "ru" to mapOf(
            "app_name" to "GGUF Chat",
            "chat" to "Чат",
            "settings" to "Настройки",
            "models" to "Модели",
            "select_model" to "Выбрать модель",
            "no_model" to "Модель не загружена",
            "load_model" to "Загрузить модель",
            "download_model" to "Скачать модель",
            "model_url" to "URL модели (GGUF)",
            "file_name" to "Имя файла (необязательно)",
            "download" to "Скачать",
            "download_hint" to "Вставьте прямую ссылку на файл .gguf, например с Hugging Face.",
            "search_models" to "Поиск моделей в интернете",
            "search_keyword" to "Ключевое слово (напр. qwen, phi, llama)",
            "max_size_mb" to "Макс. размер (МБ)",
            "search" to "Поиск",
            "search_results" to "Результаты — выберите для скачивания:",
            "no_results" to "Ничего не найдено",
            "no_limit" to "Без лимита",
            "importing_model" to "Импорт модели...",
            "model_imported" to "Модель импортирована",
            "import_failed" to "Ошибка импорта",
            "downloading_model" to "Загрузка модели...",
            "model_downloaded" to "Модель скачана",
            "download_cancelled" to "Загрузка отменена",
            "download_failed" to "Ошибка загрузки",
            "loading_model" to "Загрузка модели...",
            "model_loaded_msg" to "Модель загружена",
            "load_model_failed" to "Не удалось загрузить модель",
            "please_load_model" to "Сначала загрузите модель",
            "error_msg" to "Ошибка",
            "model_too_large" to "Модель слишком велика для этого устройства",
            "ready" to "Готово",
            "loading_memory" to "Загрузка в память...",
            "copying_model" to "Копирование файла модели...",
            "copying_mb" to "Копирование...",
            "validating_file" to "Проверка файла модели...",
            "download_complete" to "Загрузка завершена",
            "connecting" to "Подключение...",
            "downloading_mb" to "Загрузка...",
            "no_storage" to "Недостаточно места",
            "invalid_gguf" to "Некорректный GGUF-файл",
            "model_exists" to "Модель с таким именем уже существует",
            "invalid_url" to "URL должен начинаться с http:// или https://",
            "incomplete_download" to "Неполная загрузка",
            "cancelled" to "Отменено",
            "ram" to "ОЗУ",
            "free_ram" to "Освободить ОЗУ",
            "ram_free" to "свободно",
            "ram_freed" to "ОЗУ освобождена",
            "unsupported_arch" to "Архитектура модели не поддерживается этой версией приложения",
            "not_a_model" to "Это не полная языковая модель",
            "tap_import_hint" to "Нажмите +, чтобы импортировать файл модели, или воспользуйтесь поиском/загрузкой",
            "model_loaded" to "Модель загружена",
            "model_loading" to "Загрузка модели...",
            "model_error" to "Не удалось загрузить модель",
            "model_unloaded" to "Модель выгружена",
            "unload_model" to "Выгрузить модель",
            "model_file_missing" to "Файл модели не найден",
            "delete_model" to "Удалить модель",
            "model_info" to "Информация о модели",
            "architecture" to "Архитектура",
            "context_length" to "Длина контекста",
            "size" to "Размер",
            "tensors" to "Тензоры",
            "input_placeholder" to "Введите сообщение...",
            "send" to "Отправить",
            "stop" to "Стоп",
            "listening" to "Слушаю...",
            "voice_input" to "Голосовой ввод",
            "tts" to "Озвучка",
            "tts_enabled" to "Включить озвучку",
            "tts_language" to "Язык озвучки",
            "tts_rate" to "Скорость речи",
            "stt_language" to "Язык голосового ввода",
            "system_prompt" to "Системный промпт",
            "temperature" to "Температура",
            "top_p" to "Top P",
            "max_tokens" to "Макс. токенов",
            "context_size" to "Размер контекста",
            "threads" to "Потоки",
            "auto_suggest" to "Автоподсказки",
            "suggestion_count" to "Количество подсказок",
            "suggestion_doc_tokens" to "Документы в подсказках (токены)",
            "suggestions" to "Подсказки",
            "new_suggestions" to "Новые подсказки",
            "generating_suggestions" to "Генерация подсказок...",
            "no_suggestions" to "Пока нет подсказок",
            "language" to "Язык",
            "answer_language" to "Язык ответов и подсказок",
            "lang_auto" to "Как интерфейс",
            "english" to "Английский",
            "russian" to "Русский",
            "german" to "Немецкий",
            "light" to "Светлая",
            "dark" to "Тёмная",
            "green" to "Зелёная",
            "orange" to "Оранжевая",
            "light_blue" to "Голубая",
            "yellow" to "Жёлтая",
            "new_chat" to "Новый чат",
            "chat_history" to "История чатов",
            "delete_chat" to "Удалить чат",
            "cancel" to "Отмена",
            "ok" to "ОК",
            "error" to "Ошибка",
            "copy" to "Копировать",
            "copied" to "Скопировано",
            "retry" to "Повторить",
            "model_not_loaded" to "Сначала загрузите модель",
            "storage_warning" to "Недостаточно места на диске",
            "loading_progress" to "Прогресс загрузки",
            "copying_model" to "Копирование файла модели...",
            "loading_into_memory" to "Загрузка в память...",
            "ready" to "Готово",
            "chat_template" to "Шаблон чата",
            "auto" to "Авто",
            "manual" to "Вручную",
            "apply" to "Применить",
            "reset" to "Сбросить",
            "save" to "Сохранить",
            "about" to "О программе",
            "version" to "Версия",
            "model_selection" to "Выбор модели",
            "inference_settings" to "Параметры инференса",
            "voice_settings" to "Голосовые настройки",
            "suggestion_settings" to "Настройки подсказок",
            "general" to "Общие",
            "appearance" to "Внешний вид",
            "interface_section" to "Интерфейс",
            "input_position" to "Положение поля ввода",
            "position_bottom" to "Снизу",
            "position_top" to "Сверху",
            "suggestions_layout" to "Вид подсказок",
            "layout_wrap" to "С переносом",
            "layout_single_row" to "Одна строка",
            "behavior" to "Поведение",
            "advanced" to "Дополнительно",
            "export_chat" to "Экспорт чата",
            "import_chat" to "Импорт чата",
            "clear_history" to "Очистить историю",
            "search" to "Поиск",
            "search_placeholder" to "Поиск сообщений...",
            "no_results" to "Ничего не найдено",
            "today" to "Сегодня",
            "yesterday" to "Вчера",
            "this_week" to "На этой неделе",
            "older" to "Ранее",
            "message_copied" to "Сообщение скопировано",
            "model_deleted" to "Модель удалена",
            "chat_deleted" to "Чат удалён",
            "confirm_delete" to "Вы уверены, что хотите удалить?",
            "confirm" to "Подтвердить",
            "back" to "Назад",
            "next" to "Далее",
            "done" to "Готово",
            "skip" to "Пропустить",
            "close" to "Закрыть",
            "documents" to "Документы",
            "add_document" to "Добавить файл",
            "attach" to "Прикрепить",
            "attach_image" to "Прикрепить изображение",
            "take_photo" to "Сделать фото",
            "image_attached" to "Изображение прикреплено",
            "image_error" to "Не удалось загрузить изображение",
            "remove_image" to "Убрать изображение",
            "vision_unavailable" to "Изображение пропущено: загрузи мультимодальную модель с mmproj",
            "not_a_projector" to "Это не файл проектора mmproj",
            "projector_importing" to "Импорт проектора...",
            "projector_imported" to "Проектор импортирован",
            "projector_attached" to "Проектор прикреплён",
            "projector_removed" to "Проектор удалён",
            "projector" to "Проектор (mmproj)",
            "attach_projector" to "Прикрепить проектор",
            "download_projector" to "Скачать проектор",
            "remove_projector" to "Убрать проектор",
            "no_projector" to "Без проектора",
            "vision_ready" to "Ввод изображений готов",
            "text_only" to "Только текст",
            "preparing_image" to "Анализ изображения (может занять минуты)...",
            "include_projectors" to "Искать проекторы (mmproj)",
            "projector_url" to "URL проектора (mmproj)",
            "loading_projector" to "Загрузка проектора (mmproj)...",
            "document_added" to "Документ добавлен",
            "documents_empty" to "Документы не прикреплены. Их текст передаётся модели как контекст.",
            "doc_unsupported" to "Неподдерживаемый тип файла. Используй txt, md, json или html.",
            "doc_truncated" to "обрезан под контекст",
            "doc_read_error" to "Не удалось прочитать файл",
            "reading_document" to "Чтение документа...",
            "docs_budget_full" to "Лимит контекста для документов исчерпан. Сначала удали документ.",
            "remove_document" to "Удалить документ",
            "docs_context_hint" to "Использовано контекста",
            "docs_in_context" to "в контексте",
            "open" to "Открыть",
            "edit" to "Редактировать",
            "share" to "Поделиться",
            "more" to "Ещё",
            "less" to "Меньше",
            "show_more" to "Показать больше",
            "show_less" to "Показать меньше",
            "expand" to "Развернуть",
            "collapse" to "Свернуть",
            "refresh" to "Обновить",
            "reload" to "Перезагрузить",
            "update" to "Обновить",
            "download" to "Скачать",
            "upload" to "Загрузить",
            "install" to "Установить",
            "uninstall" to "Удалить",
            "enable" to "Включить",
            "disable" to "Выключить",
            "on" to "Вкл",
            "off" to "Выкл",
            "yes" to "Да",
            "no" to "Нет",
            "maybe" to "Возможно",
            "unknown" to "Неизвестно",
            "loading" to "Загрузка...",
            "processing" to "Обработка...",
            "waiting" to "Ожидание...",
            "connecting" to "Подключение...",
            "disconnecting" to "Отключение...",
            "connected" to "Подключено",
            "disconnected" to "Отключено",
            "online" to "Онлайн",
            "offline" to "Офлайн",
            "available" to "Доступно",
            "unavailable" to "Недоступно",
            "active" to "Активно",
            "inactive" to "Неактивно",
            "enabled" to "Включено",
            "disabled" to "Выключено",
            "visible" to "Видимо",
            "hidden" to "Скрыто",
            "selected" to "Выбрано",
            "unselected" to "Не выбрано",
            "checked" to "Отмечено",
            "unchecked" to "Не отмечено",
            "expanded" to "Развёрнуто",
            "collapsed" to "Свёрнуто",
            "locked" to "Заблокировано",
            "unlocked" to "Разблокировано",
            "pinned" to "Закреплено",
            "unpinned" to "Не закреплено",
            "starred" to "Избранное",
            "unstarred" to "Не избранное",
            "favorite" to "Избранное",
            "unfavorite" to "Не избранное",
            "archived" to "В архиве",
            "unarchived" to "Не в архиве",
            "deleted" to "Удалено",
            "restored" to "Восстановлено",
            "trashed" to "В корзине",
            "untrashed" to "Не в корзине",
            "spam" to "Спам",
            "not_spam" to "Не спам",
            "read" to "Прочитано",
            "unread" to "Непрочитано",
            "important" to "Важно",
            "not_important" to "Не важно",
            "urgent" to "Срочно",
            "not_urgent" to "Не срочно",
            "high" to "Высокий",
            "medium" to "Средний",
            "low" to "Низкий",
            "critical" to "Критический",
            "warning" to "Предупреждение",
            "info" to "Инфо",
            "success" to "Успех",
            "failure" to "Ошибка",
            "pending" to "В ожидании",
            "completed" to "Завершено",
            "in_progress" to "В процессе",
            "not_started" to "Не начато",
            "paused" to "Приостановлено",
            "resumed" to "Возобновлено",
            "stopped" to "Остановлено",
            "started" to "Начато",
            "finished" to "Завершено",
            "cancelled" to "Отменено",
            "scheduled" to "Запланировано",
            "overdue" to "Просрочено",
            "due" to "Срок",
            "upcoming" to "Предстоящее",
            "past" to "Прошлое",
            "present" to "Настоящее",
            "future" to "Будущее",
            "now" to "Сейчас",
            "later" to "Позже",
            "soon" to "Скоро",
            "eventually" to "В конечном счёте",
            "never" to "Никогда",
            "always" to "Всегда",
            "sometimes" to "Иногда",
            "often" to "Часто",
            "rarely" to "Редко",
            "usually" to "Обычно",
            "normally" to "Обычно",
            "typically" to "Как правило",
            "generally" to "В общем",
            "specifically" to "Конкретно",
            "particularly" to "Особенно",
            "especially" to "Особенно",
            "mainly" to "В основном",
            "mostly" to "В основном",
            "partly" to "Частично",
            "fully" to "Полностью",
            "completely" to "Полностью",
            "totally" to "Полностью",
            "absolutely" to "Абсолютно",
            "definitely" to "Определённо",
            "certainly" to "Безусловно",
            "probably" to "Вероятно",
            "possibly" to "Возможно",
            "maybe" to "Возможно",
            "perhaps" to "Возможно",
            "presumably" to "Предположительно",
            "supposedly" to "Якобы",
            "allegedly" to "Якобы",
            "apparently" to "Очевидно",
            "evidently" to "Очевидно",
            "obviously" to "Очевидно",
            "clearly" to "Очевидно",
            "plainly" to "Просто",
            "simply" to "Просто",
            "just" to "Просто",
            "only" to "Только",
            "merely" to "Только",
            "barely" to "Едва",
            "hardly" to "Едва",
            "scarcely" to "Едва",
            "nearly" to "Почти",
            "almost" to "Почти",
            "approximately" to "Примерно",
            "roughly" to "Примерно",
            "about" to "Около",
            "around" to "Около",
            "exactly" to "Точно",
            "precisely" to "Точно",
            "accurately" to "Точно",
            "correctly" to "Правильно",
            "incorrectly" to "Неправильно",
            "wrongly" to "Неправильно",
            "rightly" to "Правильно",
            "justly" to "Справедливо",
            "unjustly" to "Несправедливо",
            "fairly" to "Справедливо",
            "unfairly" to "Несправедливо",
            "equally" to "Равно",
            "unequally" to "Неравно",
            "similarly" to "Аналогично",
            "differently" to "Иначе",
            "likewise" to "Точно так же",
            "otherwise" to "Иначе",
            "else" to "Иначе",
            "instead" to "Вместо",
            "rather" to "Скорее",
            "alternatively" to "Альтернативно",
            "conversely" to "Напротив",
            "inversely" to "Напротив",
            "oppositely" to "Противоположно",
            "contrarily" to "Напротив",
            "contrastingly" to "В отличие",
            "comparatively" to "Сравнительно",
            "relatively" to "Относительно",
            "conditionally" to "Условно",
            "unconditionally" to "Безусловно",
            "indefinitely" to "Неопределённо",
            "temporarily" to "Временно",
            "permanently" to "Постоянно",
            "briefly" to "Кратко",
            "shortly" to "Скоро",
            "momentarily" to "Мгновенно",
            "instantly" to "Мгновенно",
            "immediately" to "Немедленно",
            "promptly" to "Быстро",
            "quickly" to "Быстро",
            "rapidly" to "Быстро",
            "swiftly" to "Быстро",
            "speedily" to "Быстро",
            "slowly" to "Медленно",
            "gradually" to "Постепенно",
            "steadily" to "Устойчиво",
            "continuously" to "Непрерывно",
            "continually" to "Постоянно",
            "constantly" to "Постоянно",
            "consistently" to "Последовательно",
            "persistently" to "Упорно",
            "repeatedly" to "Многократно",
            "frequently" to "Часто",
            "infrequently" to "Редко",
            "occasionally" to "Иногда",
            "periodically" to "Периодически",
            "regularly" to "Регулярно",
            "irregularly" to "Нерегулярно",
            "sporadically" to "Спорадически",
            "randomly" to "Случайно",
            "arbitrarily" to "Произвольно",
            "haphazardly" to "Беспорядочно",
            "chaotically" to "Хаотично",
            "orderly" to "Упорядоченно",
            "disorderly" to "Беспорядочно",
            "methodically" to "Методично",
            "systematically" to "Систематически",
            "logically" to "Логично",
            "illogically" to "Нелогично",
            "rationally" to "Рационально",
            "irrationally" to "Иррационально",
            "reasonably" to "Разумно",
            "unreasonably" to "Неразумно",
            "sensibly" to "Разумно",
            "insensibly" to "Неразумно",
            "wisely" to "Мудро",
            "foolishly" to "Глупо",
            "intelligently" to "Умно",
            "unintelligently" to "Глупо",
            "cleverly" to "Умно",
            "stupidly" to "Глупо",
            "brilliantly" to "Блестяще",
            "dully" to "Тупо",
            "brightly" to "Ярко",
            "darkly" to "Тёмно",
            "lightly" to "Легко",
            "heavily" to "Тяжело",
            "strongly" to "Сильно",
            "weakly" to "Слабо",
            "powerfully" to "Мощно",
            "powerlessly" to "Бессильно",
            "forcefully" to "Насильно",
            "gently" to "Нежно",
            "roughly" to "Грубо",
            "smoothly" to "Плавно",
            "softly" to "Мягко",
            "loudly" to "Громко",
            "quietly" to "Тихо",
            "silently" to "Молча",
            "noisily" to "Шумно",
            "peacefully" to "Мирно",
            "violently" to "Яростно",
            "calmly" to "Спокойно",
            "angrily" to "Сердито",
            "happily" to "Счастливо",
            "sadly" to "Грустно",
            "joyfully" to "Радостно",
            "sorrowfully" to "Скорбно",
            "cheerfully" to "Весело",
            "gloomily" to "Мрачно",
            "merrily" to "Весело",
            "solemnly" to "Торжественно",
            "seriously" to "Серьёзно",
            "jokingly" to "Шутливо",
            "facetiously" to "Шутливо",
            "flippantly" to "Легкомысленно",
            "glibly" to "Небрежно",
            "cheekily" to "Дерзко",
            "impudently" to "Нагло",
            "brazenly" to "Нагло",
            "boldly" to "Смело",
            "timidly" to "Робко",
            "shyly" to "Застенчиво",
            "bashfully" to "Стыдливо",
            "modestly" to "Скромно",
            "immodestly" to "нескромно",
            "humbly" to "Смиренно",
            "proudly" to "Гордо",
            "arrogantly" to "Вызывающе",
            "haughtily" to "Высокомерно",
            "snobbishly" to "Снобистски",
            "pretentiously" to "Претенциозно",
            "ostentatiously" to "Показушно",
            "showily" to "Показушно",
            "flashily" to "Ярко",
            "gaudily" to "Безвкусно",
            "tastefully" to "Со вкусом",
            "distastefully" to "Безвкусно",
            "elegantly" to "Элегантно",
            "inelegantly" to "Неэлегантно",
            "gracefully" to "Грациозно",
            "gracelessly" to "Неуклюже",
            "beautifully" to "Красиво",
            "uglily" to "Уродливо",
            "handsomely" to "Красиво",
            "plainly" to "Просто",
            "attractively" to "Привлекательно",
            "unattractively" to "Непривлекательно",
            "appealingly" to "Привлекательно",
            "unappealingly" to "Непривлекательно",
            "charmingly" to "Очаровательно",
            "uncharmingly" to "Неочаровательно",
            "delightfully" to "Восхитительно",
            "disgustingly" to "Отвратительно",
            "repulsively" to "Отталкивающе",
            "repellently" to "Отталкивающе",
            "offensively" to "Оскорбительно",
            "defensively" to "Защитно",
            "aggressively" to "Агрессивно",
            "passively" to "Пассивно",
            "actively" to "Активно",
            "inactively" to "Неактивно",
            "energetically" to "Энергично",
            "lethargically" to "Вяло",
            "vigorously" to "Бодро",
            "listlessly" to "Вяло",
            "dynamically" to "Динамично",
            "statically" to "Статично",
            "kinetically" to "Кинетично",
            "potentially" to "Потенциально",
            "essentially" to "По сути",
            "basically" to "В основном",
            "fundamentally" to "Фундаментально",
            "primarily" to "В первую очередь",
            "secondarily" to "Во вторую очередь",
            "chiefly" to "Главным образом",
            "principally" to "В основном",
            "largely" to "В значительной степени",
            "partially" to "Частично",
            "wholly" to "Полностью",
            "entirely" to "Полностью",
            "utterly" to "Совершенно",
            "thoroughly" to "Тщательно",
            "exhaustively" to "Исчерпывающе",
            "comprehensively" to "Всесторонне",
            "extensively" to "Широко",
            "intensively" to "Интенсивно",
            "in-depth" to "Глубоко",
            "superficially" to "Поверхностно",
            "cursorily" to "Бегло",
            "lengthily" to "Долго",
            "prolongedly" to "Долго",
            "endlessly" to "Бесконечно",
            "ceaselessly" to "Непрестанно",
            "incessantly" to "Непрестанно",
            "unceasingly" to "Непрестанно",
            "interminably" to "Бесконечно",
            "eternally" to "Вечно",
            "irrevocably" to "Безвозвратно",
            "irreversibly" to "Необратимо",
            "irreparably" to "Непоправимо",
            "irremediably" to "Безнадёжно",
            "irretrievably" to "Безвозвратно",
            "irrecoverably" to "Безвозвратно",
            "irredeemably" to "Безнадёжно",
            "unalterably" to "Неизменно",
            "unchangeably" to "Неизменно",
            "immutably" to "Неизменно",
            "invariably" to "Неизменно",
            "lastingly" to "Долговечно",
            "enduringly" to "Долговечно",
            "perennially" to "Ежегодно",
            "everlastingly" to "Вечно",
            "infinitely" to "Бесконечно",
            "boundlessly" to "Безгранично",
            "limitlessly" to "Безгранично",
            "inexhaustibly" to "Неисчерпаемо"
        )
    )

    fun getString(key: String, lang: String): String {
        val selectedLang = if (translations.containsKey(lang)) lang else "en"
        return translations[selectedLang]?.get(key) ?: translations["en"]?.get(key) ?: key
    }
}
